packages:
  - 'apps/*'
  - 'packages/*'
  - 'mini-services/*'
  - 'tools/*'
  - 'scripts/*'

catalog:
  # Core dependencies
  '@prisma/client': ^7.1.0
  '@radix-ui/*': ^1.0.0
  '@tanstack/react-query': ^5.90.12
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.1
  framer-motion: ^12.23.25
  lucide-react: ^0.556.0
  next: ^16.0.7
  prettier: ^3.7.4
  prisma: ^7.1.0
  react: ^19.2.1
  react-dom: ^19.2.1
  tailwindcss: ^4.1.17
  tsx: ^4.21.0
  typescript: ^5.9.3
  z-ai-web-dev-sdk: ^0.0.11
  zustand: ^5.0.9

overrides:
  d3-color@<3.1.0: '>=3.1.0'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  got@<11.8.5: '>=11.8.5'
  tar-fs@>=3.0.0 <3.0.7: '>=3.0.7'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'